# Generated by Django 5.1.4 on 2026-06-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('is_productive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'activity categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('action_taken', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['row_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration_hours', models.FloatField()),
                ('stated_hours', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('corrected', 'Corrected')], default='clean', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='shifts.activitycategory')),
            ],
            options={
                'ordering': ['day_date', 'start'],
            },
        ),
    ]
